import { PrismaClient } from '@prisma/client';
import { ensureAdminAccount } from '../src/modules/admin/admin-account';

const prisma = new PrismaClient();

// All 15 Cloudes and their full sub-category taxonomy, generated verbatim from
// frontend/lib/cloudes-data.ts (same names, same order) so that `slug` values
// line up exactly with the ones the frontend links to (e.g.
// /cloudes/skill?category=home-tutors). Keep the two files in sync — regenerate
// this list from cloudes-data.ts rather than hand-editing it out of sync.
const cloudes = [
  {
    name: 'Shopping Cloude',
    slug: 'shopping',
    description: 'Everyday shopping across grocery, electronics, fashion and more.',
    icon: 'ShoppingBag',
    categories: [
      'Grocery Items & Daily Use',
      'Hardware',
      'Electronics',
      'Fashion & Clothing',
      'Construction Materials',
      'Mobile',
      'Beauty Products',
      'Furniture',
      'Machine and Tools Shop',
      'Other Services / Products',
    ],
  },
  {
    name: 'Food Cloude',
    slug: 'food',
    description: 'Restaurants, food discovery, and budget-based filtering.',
    icon: 'UtensilsCrossed',
    categories: [
      'Restaurants',
      'Cloud Kitchen',
      'Kitchens',
      'Special Food',
      'Mess Food',
      'Street Food',
      'Affordable Food',
      'Budget Hotels',
      'Budget Restaurants',
      'Food Items Availability',
      'Beverage Items Availability',
      'Homemade Special Food',
      'Achar / Pickle',
      'Doodh (Milk)',
      'Makhan (Butter)',
      'Homemade Cakes',
      'Chips & Namkeen',
      'Other Services / Products',
    ],
  },
  {
    name: 'Skill & Servicing Cloude',
    slug: 'skill',
    description: 'Handmade & creative products, skill-based businesses, freelancing services and tutoring.',
    icon: 'Sparkles',
    categories: [
      'Gifts',
      'Handcraft items, Clay products, Bamboo products, etc',
      'Pooja items & pooja material',
      'Artificial jewellery',
      'Handcraft items/Art',
      'Other creative small-business products',
      'Beauty, makeup, salon & parlour products/items, Mehndi artist',
      'Cleaning products',
      'Interior & décor items',
      'Snacks and similar products',
      'T-shirts, cups & printing-related products',
      'Flex and printing services and banner',
      'Cleaning services / dry cleaning, Laundry worker',
      'Other Skill-Related Businesses',
      'Vehicle repair workers',
      'AC & electronics repair technicians',
      'Mobile & laptop repair specialists',
      'Laptop cleaning, repairing & maintenance',
      'Hair cutting & personal grooming',
      'Vehicle washing, PPF, servicing',
      'Tailor',
      'Construction work freelance (plumber, electrician, carpenter, lohar, house maker mistri, thikedar)',
      'Home tutors',
      'Coaching centres/ tuter',
      'Institutes & skill-development facilities',
      'Other Business',
      'Other Services / Products',
    ],
  },
  {
    name: 'Software Cloude',
    slug: 'software',
    description: 'Digital and professional freelancing services.',
    icon: 'Code2',
    categories: [
      'Website Design & Development',
      'E-commerce Websites',
      'WordPress / CMS Development',
      'Website Maintenance & Bug Fixing',
      'Android App Development',
      'iOS App Development',
      'Cross-platform App Development',
      'App Maintenance & Updates',
      'Digital Marketing & SEO',
      'Social Media Marketing',
      'Sales & Lead Generation',
      'Content Marketing',
      'Graphic Design',
      'Logo & Branding',
      'UI/UX Design',
      'Print & Packaging Design',
      'Photography',
      'Videography',
      'Media Production',
      'Podcast Production',
      'Architectural Design',
      '3D Modelling & Rendering',
      'Interior Design',
      'Structural Planning',
      'Document Translation',
      'Language Interpretation',
      'Subtitling & Localization',
      'Content Translation',
      'Data Entry',
      'Data Analysis',
      'Excel & Spreadsheet Work',
      'Business Reporting & Dashboards',
      'Video Editing',
      'Motion Graphics',
      'Color Grading',
      'YouTube / Reels Editing',
      '2D Animation',
      '3D Animation',
      'Explainer Videos',
      'VFX & Motion Design',
      'Other Services / Products',
    ],
  },
  {
    name: 'Financing Cloude',
    slug: 'financing',
    description: 'Loans, insurance and other financial services.',
    icon: 'BadgeIndianRupee',
    categories: [
      'Personal Loan',
      'Home Loan',
      'Business Loan',
      'Car & Vehicle Loan',
      'Gold Loan',
      'Education Loan',
      'Loan Against Property',
      'Life Insurance',
      'Health Insurance',
      'Vehicle Insurance',
      'General & Property Insurance',
      'Mutual Funds',
      'Stock Market / Demat Account',
      'SIP & Investment Advisory',
      'Fixed Deposit & Bonds',
      'Income Tax Filing (CA)',
      'GST Registration & Filing',
      'Accounting & Bookkeeping',
      'Credit Score / CIBIL Services',
      'Bank Correspondent / Mini Bank',
      'Credit Card Services',
      'Money Transfer (DMT)',
      'ATM / CSP Agent',
      'Other Services / Products',
    ],
  },
  {
    name: 'Jobs Cloude',
    slug: 'jobs',
    description: 'Categorised job listings across skill levels — a dedicated job portal module.',
    icon: 'Briefcase',
    categories: ['IT & Digital Jobs', 'Operational Jobs', 'Skilled Trade Jobs'],
  },
  {
    name: 'Booking Cloude',
    slug: 'booking',
    description: 'Travel, vehicle, and event booking services.',
    icon: 'CalendarCheck',
    categories: [
      'Tour Packages',
      'Hotels',
      'Rooms & Guest Houses',
      'Cab, Bus, Truck',
      'Delivery, Package & Movers services',
      'Courier services',
      'Party, Events & Birthday function booking',
      'Other Services / Products',
    ],
  },
  {
    name: 'Wedding Cloude',
    slug: 'wedding',
    description: 'Everything for planning a wedding, from venues to pandits.',
    icon: 'Heart',
    categories: [
      'Hotel Booking',
      'Banquet Hall Booking',
      'Wedding Venue Booking',
      'Pooja Items',
      'Pandit Booking',
      'Wedding Furniture',
      'Furniture Rental for Events',
      'Wedding Manager',
      'Wedding Planning Services',
      'Studio (Cameraman)',
      'Other Wedding-Related Services',
      'Other Services / Products',
    ],
  },
  {
    name: 'Property Cloude',
    slug: 'property',
    description: 'Renting, buying, and property-related professional services.',
    icon: 'Home',
    categories: [
      'Hostel (rent)',
      'Guest House (rent)',
      'Room (rent)',
      'PG (rent)',
      'Shop (rent or sale)',
      'Office (rent or sale)',
      'Flat (rent or sale)',
      'Warehouse (rent or sale)',
      'Plot (rent or sale)',
      'Construction & Architecture teams',
      'Construction Material Shop (Plumber, Electrician, Balu, Cement, Carpenter, Paint, Sariya, Lohar, Steel, Home Decor, etc.)',
      'Design teams / Engineers / Mistri / Thikedar',
      'Electric shop',
      'Paint shop',
      'Carpentry shop',
      'Office/marketing/professional services for new projects',
      'Other Services / Products',
    ],
  },
  {
    name: 'Rent Cloude',
    slug: 'rent',
    description: 'General rental marketplace across categories.',
    icon: 'KeyRound',
    categories: [
      'Cars',
      'Bikes & Scooters',
      'Commercial Vehicles',
      'Flats & Apartments',
      'Shops & Offices',
      'Rooms & PG',
      'Furniture Rental',
      'Appliances Rental',
      'Décor Items Rental',
      'Laptops & Computers',
      'Cameras',
      'Mobile Phones',
      'Wedding & Party Wear',
      'Costumes',
      'Accessories',
      'Construction Equipment',
      'Power Tools',
      'Industrial Machines',
      'Other Services / Products',
    ],
  },
  {
    name: 'Mini Factory / Manufacturing Cloude',
    slug: 'manufacturing',
    description: 'Small-scale manufacturing and homemade-product businesses.',
    icon: 'Factory',
    categories: [
      'Pickles, Papad & Snacks',
      'Bakery & Confectionery',
      'Spices & Masala Powder',
      'Packaged & Homemade Foods',
      'Handicrafts',
      'Pottery & Clay Products',
      'Bamboo & Cane Products',
      'Handmade Decor Items',
      'Tailoring & Stitching Units',
      'Embroidery & Zari Work',
      'Garment Manufacturing',
      'Handloom & Weaving',
      'Handmade Soap',
      'Candle Making',
      'Cosmetics & Skincare Products',
      'Essential Oils & Perfumes',
      'Furniture & Woodwork',
      'Metal Fabrication & Welding',
      'Small Machine Parts',
      'Plastic & Rubber Products',
      'Packaging Services',
      'Printing & Labeling',
      'Agarbatti & Incense Manufacturing',
      'Pooja Product Manufacturing',
      'Other Services / Products',
    ],
  },
  {
    name: 'Education Cloude',
    slug: 'education',
    description: 'Coaching, courses, institutes and home tutors.',
    icon: 'GraduationCap',
    categories: [
      'Academic Coaching (School/College)',
      'IT & Programming Coaching',
      'Competitive Exam Coaching',
      'Personality Development Coaching',
      'Certificate Courses',
      'Online Courses',
      'Skill-based Short Courses',
      'Diploma Courses',
      'Educational Institutes',
      'Vocational Training Institutes',
      'Technical Institutes',
      'Skill Development Centres',
      'School Subject Tutors',
      'Language Tutors',
      'Music & Art Tutors',
      'Exam Preparation Tutors',
      'Computer & Digital Skills',
      'Communication & Soft Skills',
      'Vocational Skill Training',
      'Career Counselling',
      'Sports Coaching',
      'Dance & Music Classes',
      'Art & Craft Classes',
      'Fitness & Yoga Classes',
      'Educational Consultancy',
      'Study Material & Books',
      'Used Books / Second-hand Books',
      'Stationery & Book Shop',
      'Admission Guidance',
      'Other Educational Services',
    ],
  },
  {
    name: 'Agriculture & Farmer Cloude',
    slug: 'agriculture',
    description: 'Farming inputs, fresh vegetables and fruits for farmers and buyers.',
    icon: 'Leaf',
    categories: [
      'Potato',
      'Onion',
      'Tomato',
      'Cauliflower',
      'Cabbage',
      'Brinjal',
      'Green Chilli',
      'Capsicum',
      'Peas',
      'Spinach',
      'Other Vegetables',
      'Litchi',
      'Apple',
      'Orange',
      'Banana',
      'Mango',
      'Grapes',
      'Watermelon',
      'Papaya',
      'Pomegranate',
      'Other Fruits',
      'Street Vendor',
      'Pushcart (Thela) Vendor',
      'Mobile Fruit & Vegetable Cart',
      'Tractor Rent',
      'Harvester Rent',
      'Rotavator Rent',
      'Plough / Cultivator Rent',
      'Other Farming Machine Rent',
      'Tata Ace Mini Truck',
      'Goods Loading & Transport',
      'Farm-to-Market Delivery',
      'Insecticides',
      'Fungicides',
      'Herbicides / Weedicides',
      'Bio-Pesticides',
      'Fertilizers',
      'Plant Growth Regulators',
      'Agri-Input Store',
      'Other Services / Products',
    ],
  },
  {
    name: 'Clinic & Doctors Cloude',
    slug: 'clinic-doctors',
    description: 'Healthcare discovery — doctors, hospitals and diagnostics.',
    icon: 'Stethoscope',
    categories: [
      'Cardiologist / Heart Specialist',
      'Kidney Specialist',
      'Dermatologist',
      'ENT Specialist',
      'Orthopedic',
      'Neurologist',
      'Pediatrician',
      'General Physician',
      'Other Specialists',
      'Hospitals Offering Treatment',
      'Comparative & Affordable Options',
      'Hospital Details & Facilities',
      'Emergency Services',
      'Physiotherapy',
      'X-Ray',
      'Radiology',
      'Pathology Lab',
      'Other Healthcare-Related Services',
      'Other Services / Products',
    ],
  },
  {
    name: 'Sports & fitness & gym Cloude',
    slug: 'sports-fitness-gym',
    description: 'Sports academies, fitness training and gym services.',
    icon: 'Dumbbell',
    categories: [
      'Coaches & Trainers',
      'Cricket Academy',
      'Basketball Academy',
      'Badminton Academy',
      'Volleyball Academy',
      'Yoga Trainer',
      'Police Physical Training',
      'Govt Exam Physical Training',
      'Karate Academy',
      'Taekwondo Academy',
      'Gym Equipment & Items',
      'Exercise & Workout Plans',
      'Gym Trainer',
      'Other Services / Products',
    ],
  },
];

function slugify(text: string) {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

async function main() {
  console.log('Seeding Cloudes & Categories...');

  for (const [index, c] of cloudes.entries()) {
    const cloude = await prisma.cloude.upsert({
      where: { slug: c.slug },
      update: { name: c.name, description: c.description, icon: c.icon, sortOrder: index },
      create: {
        name: c.name,
        slug: c.slug,
        description: c.description,
        icon: c.icon,
        sortOrder: index,
      },
    });

    // Names/slugs may have changed since the last seed run (categories were
    // rewritten to match the frontend's fuller taxonomy) — drop any category
    // from a previous seed that's no longer in this list, as long as it has
    // no listings/jobs attached to it yet.
    const currentSlugs = c.categories.map(slugify);
    await prisma.category.deleteMany({
      where: {
        cloudeId: cloude.id,
        slug: { notIn: currentSlugs },
        listings: { none: {} },
        jobs: { none: {} },
      },
    });

    for (const catName of c.categories) {
      const catSlug = slugify(catName);
      await prisma.category.upsert({
        where: { cloudeId_slug: { cloudeId: cloude.id, slug: catSlug } },
        update: { name: catName },
        create: {
          name: catName,
          slug: catSlug,
          cloudeId: cloude.id,
          attributeSchema: [
            { key: 'title', label: 'Ad Title', type: 'text', required: true, maxLength: 70 },
            { key: 'description', label: 'Description', type: 'textarea', required: true, maxLength: 4096 },
          ],
        },
      });
    }
  }

  // Drop any Cloude that no longer exists in the frontend taxonomy, as long as
  // nothing has been posted under it yet.
  const currentCloudeSlugs = cloudes.map((c) => c.slug);
  await prisma.cloude.deleteMany({
    where: { slug: { notIn: currentCloudeSlugs }, listings: { none: {} } },
  });

  // The one and only admin (admin@gmail.com) — also ensured on every backend start.
  await ensureAdminAccount(prisma);

  console.log('Seed complete.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
